site_name: CirtusAI SDK Documentation
site_description: "Comprehensive Python SDK for autonomous AI agents, multi-chain wallets, and enterprise compliance"
site_url: https://github.com/Cirtus-AI/cirtusai_sdk
repo_url: https://github.com/Cirtus-AI/cirtusai_sdk
docs_dir: docs

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Authentication: authentication.md
  - Agent Management: agents.md
  - Wallet Operations: wallets.md
  - Email Services: email.md
  - Security & Compliance: security.md
  - Blockchain Infrastructure: blockchain.md
